// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPeGW_wvnTTW1iJbndEgbJIefaX-KF_5Y',
    appId: '1:421468289426:web:bf801aa2d25106b1ca294b',
    messagingSenderId: '421468289426',
    projectId: 'nhantri-52a8d',
    authDomain: 'nhantri-52a8d.firebaseapp.com',
    databaseURL: 'https://nhantri-52a8d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nhantri-52a8d.firebasestorage.app',
    measurementId: 'G-H0PTXF0EGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvNK6NMb7rGu0qilc72-J0bE2RLQ3gGIY',
    appId: '1:421468289426:android:2bbe0c53dfe02d2dca294b',
    messagingSenderId: '421468289426',
    projectId: 'nhantri-52a8d',
    databaseURL: 'https://nhantri-52a8d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nhantri-52a8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDC6JaPgeuY-sOoK2WkR9ORMjEGGcA260',
    appId: '1:421468289426:ios:abf80e4c5faa567aca294b',
    messagingSenderId: '421468289426',
    projectId: 'nhantri-52a8d',
    databaseURL: 'https://nhantri-52a8d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nhantri-52a8d.firebasestorage.app',
    iosBundleId: 'com.example.appNhanTri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDC6JaPgeuY-sOoK2WkR9ORMjEGGcA260',
    appId: '1:421468289426:ios:abf80e4c5faa567aca294b',
    messagingSenderId: '421468289426',
    projectId: 'nhantri-52a8d',
    databaseURL: 'https://nhantri-52a8d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nhantri-52a8d.firebasestorage.app',
    iosBundleId: 'com.example.appNhanTri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPeGW_wvnTTW1iJbndEgbJIefaX-KF_5Y',
    appId: '1:421468289426:web:9f95c4cb76f942e0ca294b',
    messagingSenderId: '421468289426',
    projectId: 'nhantri-52a8d',
    authDomain: 'nhantri-52a8d.firebaseapp.com',
    databaseURL: 'https://nhantri-52a8d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nhantri-52a8d.firebasestorage.app',
    measurementId: 'G-MZXXSKTQCL',
  );
}
